"use client";

type Props = {
  tenantsNewBaseHref: string; // "/tenants/new?returnTo="
  returnToBasePath: string;   // "/properties/<id>/leases/new"
  formId: string;             // "leaseForm"
};

function qsEncode(v: string) {
  return encodeURIComponent(v ?? "");
}

export default function AddTenantButton({
  tenantsNewBaseHref,
  returnToBasePath,
  formId,
}: Props) {
  function handleClick() {
    const form = document.getElementById(formId) as HTMLFormElement | null;

    if (!form) {
      window.location.href = `${tenantsNewBaseHref}${qsEncode(returnToBasePath)}`;
      return;
    }

    const getVal = (name: string) => {
      const el = form.elements.namedItem(name) as
        | HTMLInputElement
        | HTMLSelectElement
        | null;
      return el?.value ?? "";
    };

    const getChecked = (name: string) => {
      const el = form.elements.namedItem(name) as HTMLInputElement | null;
      return el?.checked ? "1" : "0";
    };

    const startDate = getVal("startDate");
    const endDate = getVal("endDate");
    const unitLabel = getVal("unitLabel");
    const rentAmount = getVal("rentAmount");
    const dueDay = getVal("dueDay");
    const deposit = getVal("deposit");
    const status = getVal("status");
    const managedByPm = getChecked("managedByPm");
    const notes = getVal("notes");

    // Collect selected tenantIds from hidden inputs generated by TenantPicker
    const tenantInputs = form.querySelectorAll<HTMLInputElement>('input[name="tenantIds"]');
    const selectedTenantIds = Array.from(tenantInputs)
      .map((i) => i.value)
      .filter(Boolean);

    const returnTo =
      `${returnToBasePath}` +
      `?startDate=${qsEncode(startDate)}` +
      `&endDate=${qsEncode(endDate)}` +
      `&unitLabel=${qsEncode(unitLabel)}` +
      `&rentAmount=${qsEncode(rentAmount)}` +
      `&dueDay=${qsEncode(dueDay)}` +
      `&deposit=${qsEncode(deposit)}` +
      `&status=${qsEncode(status)}` +
      `&managedByPm=${qsEncode(managedByPm)}` +
      `&notes=${qsEncode(notes)}` +
      selectedTenantIds.map((id) => `&tenantIds=${qsEncode(id)}`).join("");

    window.location.href = `${tenantsNewBaseHref}${qsEncode(returnTo)}`;
  }

  return (
    <button type="button" className="ll_btnWarning" onClick={handleClick}>
      Add tenant
    </button>
  );
}
